//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.23 at 05:12:29 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://schemas.ppsr.gov.au/2011/04/data", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package au.gov.ppsr;
