package au.gov.ppsr.schemas._2011._04.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-02-23T17:25:30.647+11:00
 * Generated source version: 2.7.10
 * 
 */
@WebServiceClient(name = "Ppsr", 
                  wsdlLocation = "file:/Users/murtaza/Workspace/ppsr/ppsr-apache/src/main/resources/schemas.ppsr.gov.au.2011.04.services.wsdl",
                  targetNamespace = "http://schemas.ppsr.gov.au/2011/04/services") 
public class Ppsr extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://schemas.ppsr.gov.au/2011/04/services", "Ppsr");
    public final static QName CollateralRegistrationSoap12Mtom = new QName("http://schemas.ppsr.gov.au/2011/04/services", "CollateralRegistrationSoap12Mtom");
    public final static QName CollateralRegistrationSoap11Mtom = new QName("http://schemas.ppsr.gov.au/2011/04/services", "CollateralRegistrationSoap11Mtom");
    public final static QName CollateralRegistrationSoap11 = new QName("http://schemas.ppsr.gov.au/2011/04/services", "CollateralRegistrationSoap11");
    public final static QName CollateralRegistrationSoap12 = new QName("http://schemas.ppsr.gov.au/2011/04/services", "CollateralRegistrationSoap12");
    public final static QName CollateralRegistrationSearchSoap11Mtom = new QName("http://schemas.ppsr.gov.au/2011/04/services", "CollateralRegistrationSearchSoap11Mtom");
    public final static QName CollateralRegistrationSearchSoap12Mtom = new QName("http://schemas.ppsr.gov.au/2011/04/services", "CollateralRegistrationSearchSoap12Mtom");
    public final static QName CollateralRegistrationSearchSoap11 = new QName("http://schemas.ppsr.gov.au/2011/04/services", "CollateralRegistrationSearchSoap11");
    public final static QName CollateralRegistrationSearchSoap12 = new QName("http://schemas.ppsr.gov.au/2011/04/services", "CollateralRegistrationSearchSoap12");
    public final static QName ReportSoap12Mtom = new QName("http://schemas.ppsr.gov.au/2011/04/services", "ReportSoap12Mtom");
    public final static QName ReportSoap11Mtom = new QName("http://schemas.ppsr.gov.au/2011/04/services", "ReportSoap11Mtom");
    public final static QName ReportSoap11 = new QName("http://schemas.ppsr.gov.au/2011/04/services", "ReportSoap11");
    public final static QName ReportSoap12 = new QName("http://schemas.ppsr.gov.au/2011/04/services", "ReportSoap12");
    public final static QName B2GMailboxSoap12Mtom = new QName("http://schemas.ppsr.gov.au/2011/04/services", "B2GMailboxSoap12Mtom");
    public final static QName B2GMailboxSoap12 = new QName("http://schemas.ppsr.gov.au/2011/04/services", "B2GMailboxSoap12");
    public final static QName B2GMailboxSoap11 = new QName("http://schemas.ppsr.gov.au/2011/04/services", "B2GMailboxSoap11");
    public final static QName B2GMailboxSoap11Mtom = new QName("http://schemas.ppsr.gov.au/2011/04/services", "B2GMailboxSoap11Mtom");
    public final static QName SecuredPartyGroupSoap11 = new QName("http://schemas.ppsr.gov.au/2011/04/services", "SecuredPartyGroupSoap11");
    public final static QName SecuredPartyGroupSoap12 = new QName("http://schemas.ppsr.gov.au/2011/04/services", "SecuredPartyGroupSoap12");
    public final static QName RegisterOperationsSoap12 = new QName("http://schemas.ppsr.gov.au/2011/04/services", "RegisterOperationsSoap12");
    public final static QName RegisterOperationsSoap11 = new QName("http://schemas.ppsr.gov.au/2011/04/services", "RegisterOperationsSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/murtaza/Workspace/ppsr/ppsr-apache/src/main/resources/schemas.ppsr.gov.au.2011.04.services.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Ppsr.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/murtaza/Workspace/ppsr/ppsr-apache/src/main/resources/schemas.ppsr.gov.au.2011.04.services.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Ppsr(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Ppsr(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Ppsr() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns CollateralRegistrationService
     */
    @WebEndpoint(name = "CollateralRegistrationSoap12Mtom")
    public CollateralRegistrationService getCollateralRegistrationSoap12Mtom() {
        return super.getPort(CollateralRegistrationSoap12Mtom, CollateralRegistrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CollateralRegistrationService
     */
    @WebEndpoint(name = "CollateralRegistrationSoap12Mtom")
    public CollateralRegistrationService getCollateralRegistrationSoap12Mtom(WebServiceFeature... features) {
        return super.getPort(CollateralRegistrationSoap12Mtom, CollateralRegistrationService.class, features);
    }
    /**
     *
     * @return
     *     returns CollateralRegistrationService
     */
    @WebEndpoint(name = "CollateralRegistrationSoap11Mtom")
    public CollateralRegistrationService getCollateralRegistrationSoap11Mtom() {
        return super.getPort(CollateralRegistrationSoap11Mtom, CollateralRegistrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CollateralRegistrationService
     */
    @WebEndpoint(name = "CollateralRegistrationSoap11Mtom")
    public CollateralRegistrationService getCollateralRegistrationSoap11Mtom(WebServiceFeature... features) {
        return super.getPort(CollateralRegistrationSoap11Mtom, CollateralRegistrationService.class, features);
    }
    /**
     *
     * @return
     *     returns CollateralRegistrationService
     */
    @WebEndpoint(name = "CollateralRegistrationSoap11")
    public CollateralRegistrationService getCollateralRegistrationSoap11() {
        return super.getPort(CollateralRegistrationSoap11, CollateralRegistrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CollateralRegistrationService
     */
    @WebEndpoint(name = "CollateralRegistrationSoap11")
    public CollateralRegistrationService getCollateralRegistrationSoap11(WebServiceFeature... features) {
        return super.getPort(CollateralRegistrationSoap11, CollateralRegistrationService.class, features);
    }
    /**
     *
     * @return
     *     returns CollateralRegistrationService
     */
    @WebEndpoint(name = "CollateralRegistrationSoap12")
    public CollateralRegistrationService getCollateralRegistrationSoap12() {
        return super.getPort(CollateralRegistrationSoap12, CollateralRegistrationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CollateralRegistrationService
     */
    @WebEndpoint(name = "CollateralRegistrationSoap12")
    public CollateralRegistrationService getCollateralRegistrationSoap12(WebServiceFeature... features) {
        return super.getPort(CollateralRegistrationSoap12, CollateralRegistrationService.class, features);
    }
    /**
     *
     * @return
     *     returns CollateralRegistrationSearchService
     */
    @WebEndpoint(name = "CollateralRegistrationSearchSoap11Mtom")
    public CollateralRegistrationSearchService getCollateralRegistrationSearchSoap11Mtom() {
        return super.getPort(CollateralRegistrationSearchSoap11Mtom, CollateralRegistrationSearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CollateralRegistrationSearchService
     */
    @WebEndpoint(name = "CollateralRegistrationSearchSoap11Mtom")
    public CollateralRegistrationSearchService getCollateralRegistrationSearchSoap11Mtom(WebServiceFeature... features) {
        return super.getPort(CollateralRegistrationSearchSoap11Mtom, CollateralRegistrationSearchService.class, features);
    }
    /**
     *
     * @return
     *     returns CollateralRegistrationSearchService
     */
    @WebEndpoint(name = "CollateralRegistrationSearchSoap12Mtom")
    public CollateralRegistrationSearchService getCollateralRegistrationSearchSoap12Mtom() {
        return super.getPort(CollateralRegistrationSearchSoap12Mtom, CollateralRegistrationSearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CollateralRegistrationSearchService
     */
    @WebEndpoint(name = "CollateralRegistrationSearchSoap12Mtom")
    public CollateralRegistrationSearchService getCollateralRegistrationSearchSoap12Mtom(WebServiceFeature... features) {
        return super.getPort(CollateralRegistrationSearchSoap12Mtom, CollateralRegistrationSearchService.class, features);
    }
    /**
     *
     * @return
     *     returns CollateralRegistrationSearchService
     */
    @WebEndpoint(name = "CollateralRegistrationSearchSoap11")
    public CollateralRegistrationSearchService getCollateralRegistrationSearchSoap11() {
        return super.getPort(CollateralRegistrationSearchSoap11, CollateralRegistrationSearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CollateralRegistrationSearchService
     */
    @WebEndpoint(name = "CollateralRegistrationSearchSoap11")
    public CollateralRegistrationSearchService getCollateralRegistrationSearchSoap11(WebServiceFeature... features) {
        return super.getPort(CollateralRegistrationSearchSoap11, CollateralRegistrationSearchService.class, features);
    }
    /**
     *
     * @return
     *     returns CollateralRegistrationSearchService
     */
    @WebEndpoint(name = "CollateralRegistrationSearchSoap12")
    public CollateralRegistrationSearchService getCollateralRegistrationSearchSoap12() {
        return super.getPort(CollateralRegistrationSearchSoap12, CollateralRegistrationSearchService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CollateralRegistrationSearchService
     */
    @WebEndpoint(name = "CollateralRegistrationSearchSoap12")
    public CollateralRegistrationSearchService getCollateralRegistrationSearchSoap12(WebServiceFeature... features) {
        return super.getPort(CollateralRegistrationSearchSoap12, CollateralRegistrationSearchService.class, features);
    }
    /**
     *
     * @return
     *     returns Report
     */
    @WebEndpoint(name = "ReportSoap12Mtom")
    public Report getReportSoap12Mtom() {
        return super.getPort(ReportSoap12Mtom, Report.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Report
     */
    @WebEndpoint(name = "ReportSoap12Mtom")
    public Report getReportSoap12Mtom(WebServiceFeature... features) {
        return super.getPort(ReportSoap12Mtom, Report.class, features);
    }
    /**
     *
     * @return
     *     returns Report
     */
    @WebEndpoint(name = "ReportSoap11Mtom")
    public Report getReportSoap11Mtom() {
        return super.getPort(ReportSoap11Mtom, Report.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Report
     */
    @WebEndpoint(name = "ReportSoap11Mtom")
    public Report getReportSoap11Mtom(WebServiceFeature... features) {
        return super.getPort(ReportSoap11Mtom, Report.class, features);
    }
    /**
     *
     * @return
     *     returns Report
     */
    @WebEndpoint(name = "ReportSoap11")
    public Report getReportSoap11() {
        return super.getPort(ReportSoap11, Report.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Report
     */
    @WebEndpoint(name = "ReportSoap11")
    public Report getReportSoap11(WebServiceFeature... features) {
        return super.getPort(ReportSoap11, Report.class, features);
    }
    /**
     *
     * @return
     *     returns Report
     */
    @WebEndpoint(name = "ReportSoap12")
    public Report getReportSoap12() {
        return super.getPort(ReportSoap12, Report.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Report
     */
    @WebEndpoint(name = "ReportSoap12")
    public Report getReportSoap12(WebServiceFeature... features) {
        return super.getPort(ReportSoap12, Report.class, features);
    }
    /**
     *
     * @return
     *     returns B2GMailboxService
     */
    @WebEndpoint(name = "B2GMailboxSoap12Mtom")
    public B2GMailboxService getB2GMailboxSoap12Mtom() {
        return super.getPort(B2GMailboxSoap12Mtom, B2GMailboxService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns B2GMailboxService
     */
    @WebEndpoint(name = "B2GMailboxSoap12Mtom")
    public B2GMailboxService getB2GMailboxSoap12Mtom(WebServiceFeature... features) {
        return super.getPort(B2GMailboxSoap12Mtom, B2GMailboxService.class, features);
    }
    /**
     *
     * @return
     *     returns B2GMailboxService
     */
    @WebEndpoint(name = "B2GMailboxSoap12")
    public B2GMailboxService getB2GMailboxSoap12() {
        return super.getPort(B2GMailboxSoap12, B2GMailboxService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns B2GMailboxService
     */
    @WebEndpoint(name = "B2GMailboxSoap12")
    public B2GMailboxService getB2GMailboxSoap12(WebServiceFeature... features) {
        return super.getPort(B2GMailboxSoap12, B2GMailboxService.class, features);
    }
    /**
     *
     * @return
     *     returns B2GMailboxService
     */
    @WebEndpoint(name = "B2GMailboxSoap11")
    public B2GMailboxService getB2GMailboxSoap11() {
        return super.getPort(B2GMailboxSoap11, B2GMailboxService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns B2GMailboxService
     */
    @WebEndpoint(name = "B2GMailboxSoap11")
    public B2GMailboxService getB2GMailboxSoap11(WebServiceFeature... features) {
        return super.getPort(B2GMailboxSoap11, B2GMailboxService.class, features);
    }
    /**
     *
     * @return
     *     returns B2GMailboxService
     */
    @WebEndpoint(name = "B2GMailboxSoap11Mtom")
    public B2GMailboxService getB2GMailboxSoap11Mtom() {
        return super.getPort(B2GMailboxSoap11Mtom, B2GMailboxService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns B2GMailboxService
     */
    @WebEndpoint(name = "B2GMailboxSoap11Mtom")
    public B2GMailboxService getB2GMailboxSoap11Mtom(WebServiceFeature... features) {
        return super.getPort(B2GMailboxSoap11Mtom, B2GMailboxService.class, features);
    }
    /**
     *
     * @return
     *     returns SecuredPartyGroupService
     */
    @WebEndpoint(name = "SecuredPartyGroupSoap11")
    public SecuredPartyGroupService getSecuredPartyGroupSoap11() {
        return super.getPort(SecuredPartyGroupSoap11, SecuredPartyGroupService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecuredPartyGroupService
     */
    @WebEndpoint(name = "SecuredPartyGroupSoap11")
    public SecuredPartyGroupService getSecuredPartyGroupSoap11(WebServiceFeature... features) {
        return super.getPort(SecuredPartyGroupSoap11, SecuredPartyGroupService.class, features);
    }
    /**
     *
     * @return
     *     returns SecuredPartyGroupService
     */
    @WebEndpoint(name = "SecuredPartyGroupSoap12")
    public SecuredPartyGroupService getSecuredPartyGroupSoap12() {
        return super.getPort(SecuredPartyGroupSoap12, SecuredPartyGroupService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SecuredPartyGroupService
     */
    @WebEndpoint(name = "SecuredPartyGroupSoap12")
    public SecuredPartyGroupService getSecuredPartyGroupSoap12(WebServiceFeature... features) {
        return super.getPort(SecuredPartyGroupSoap12, SecuredPartyGroupService.class, features);
    }
    /**
     *
     * @return
     *     returns RegisterOperationsService
     */
    @WebEndpoint(name = "RegisterOperationsSoap12")
    public RegisterOperationsService getRegisterOperationsSoap12() {
        return super.getPort(RegisterOperationsSoap12, RegisterOperationsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegisterOperationsService
     */
    @WebEndpoint(name = "RegisterOperationsSoap12")
    public RegisterOperationsService getRegisterOperationsSoap12(WebServiceFeature... features) {
        return super.getPort(RegisterOperationsSoap12, RegisterOperationsService.class, features);
    }
    /**
     *
     * @return
     *     returns RegisterOperationsService
     */
    @WebEndpoint(name = "RegisterOperationsSoap11")
    public RegisterOperationsService getRegisterOperationsSoap11() {
        return super.getPort(RegisterOperationsSoap11, RegisterOperationsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RegisterOperationsService
     */
    @WebEndpoint(name = "RegisterOperationsSoap11")
    public RegisterOperationsService getRegisterOperationsSoap11(WebServiceFeature... features) {
        return super.getPort(RegisterOperationsSoap11, RegisterOperationsService.class, features);
    }

}
