
package au.gov.ppsr.schemas._2011._04.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-02-23T17:25:30.545+11:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "PpsrRegisterOperationsChangeB2GPasswordValidationFaultDetail", targetNamespace = "http://schemas.ppsr.gov.au/faults")
public class RegisterOperationsServiceChangeB2GPasswordPpsrRegisterOperationsChangeB2GPasswordValidationFaultDetailFaultFaultMessage extends Exception {
    
    private au.gov.ppsr.schemas.faults.PpsrRegisterOperationsChangeB2GPasswordValidationFaultDetail ppsrRegisterOperationsChangeB2GPasswordValidationFaultDetail;

    public RegisterOperationsServiceChangeB2GPasswordPpsrRegisterOperationsChangeB2GPasswordValidationFaultDetailFaultFaultMessage() {
        super();
    }
    
    public RegisterOperationsServiceChangeB2GPasswordPpsrRegisterOperationsChangeB2GPasswordValidationFaultDetailFaultFaultMessage(String message) {
        super(message);
    }
    
    public RegisterOperationsServiceChangeB2GPasswordPpsrRegisterOperationsChangeB2GPasswordValidationFaultDetailFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public RegisterOperationsServiceChangeB2GPasswordPpsrRegisterOperationsChangeB2GPasswordValidationFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrRegisterOperationsChangeB2GPasswordValidationFaultDetail ppsrRegisterOperationsChangeB2GPasswordValidationFaultDetail) {
        super(message);
        this.ppsrRegisterOperationsChangeB2GPasswordValidationFaultDetail = ppsrRegisterOperationsChangeB2GPasswordValidationFaultDetail;
    }

    public RegisterOperationsServiceChangeB2GPasswordPpsrRegisterOperationsChangeB2GPasswordValidationFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrRegisterOperationsChangeB2GPasswordValidationFaultDetail ppsrRegisterOperationsChangeB2GPasswordValidationFaultDetail, Throwable cause) {
        super(message, cause);
        this.ppsrRegisterOperationsChangeB2GPasswordValidationFaultDetail = ppsrRegisterOperationsChangeB2GPasswordValidationFaultDetail;
    }

    public au.gov.ppsr.schemas.faults.PpsrRegisterOperationsChangeB2GPasswordValidationFaultDetail getFaultInfo() {
        return this.ppsrRegisterOperationsChangeB2GPasswordValidationFaultDetail;
    }
}
