
package au.gov.ppsr.schemas._2011._04.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-02-23T17:25:30.269+11:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "PpsrReportValidationFaultDetail", targetNamespace = "http://schemas.ppsr.gov.au/faults")
public class ReportRequestReportPpsrReportValidationFaultDetailFaultFaultMessage extends Exception {
    
    private au.gov.ppsr.schemas.faults.PpsrReportValidationFaultDetail ppsrReportValidationFaultDetail;

    public ReportRequestReportPpsrReportValidationFaultDetailFaultFaultMessage() {
        super();
    }
    
    public ReportRequestReportPpsrReportValidationFaultDetailFaultFaultMessage(String message) {
        super(message);
    }
    
    public ReportRequestReportPpsrReportValidationFaultDetailFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public ReportRequestReportPpsrReportValidationFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrReportValidationFaultDetail ppsrReportValidationFaultDetail) {
        super(message);
        this.ppsrReportValidationFaultDetail = ppsrReportValidationFaultDetail;
    }

    public ReportRequestReportPpsrReportValidationFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrReportValidationFaultDetail ppsrReportValidationFaultDetail, Throwable cause) {
        super(message, cause);
        this.ppsrReportValidationFaultDetail = ppsrReportValidationFaultDetail;
    }

    public au.gov.ppsr.schemas.faults.PpsrReportValidationFaultDetail getFaultInfo() {
        return this.ppsrReportValidationFaultDetail;
    }
}
