
package au.gov.ppsr.schemas._2011._04.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-02-23T17:25:30.450+11:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "PpsrSecuredPartyGroupUpdateFaultDetail", targetNamespace = "http://schemas.ppsr.gov.au/faults")
public class SecuredPartyGroupServiceUpdateSecuredPartyGroupPpsrSecuredPartyGroupUpdateFaultDetailFaultFaultMessage extends Exception {
    
    private au.gov.ppsr.schemas.faults.PpsrSecuredPartyGroupUpdateFaultDetail ppsrSecuredPartyGroupUpdateFaultDetail;

    public SecuredPartyGroupServiceUpdateSecuredPartyGroupPpsrSecuredPartyGroupUpdateFaultDetailFaultFaultMessage() {
        super();
    }
    
    public SecuredPartyGroupServiceUpdateSecuredPartyGroupPpsrSecuredPartyGroupUpdateFaultDetailFaultFaultMessage(String message) {
        super(message);
    }
    
    public SecuredPartyGroupServiceUpdateSecuredPartyGroupPpsrSecuredPartyGroupUpdateFaultDetailFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public SecuredPartyGroupServiceUpdateSecuredPartyGroupPpsrSecuredPartyGroupUpdateFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrSecuredPartyGroupUpdateFaultDetail ppsrSecuredPartyGroupUpdateFaultDetail) {
        super(message);
        this.ppsrSecuredPartyGroupUpdateFaultDetail = ppsrSecuredPartyGroupUpdateFaultDetail;
    }

    public SecuredPartyGroupServiceUpdateSecuredPartyGroupPpsrSecuredPartyGroupUpdateFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrSecuredPartyGroupUpdateFaultDetail ppsrSecuredPartyGroupUpdateFaultDetail, Throwable cause) {
        super(message, cause);
        this.ppsrSecuredPartyGroupUpdateFaultDetail = ppsrSecuredPartyGroupUpdateFaultDetail;
    }

    public au.gov.ppsr.schemas.faults.PpsrSecuredPartyGroupUpdateFaultDetail getFaultInfo() {
        return this.ppsrSecuredPartyGroupUpdateFaultDetail;
    }
}
