
package au.gov.ppsr.schemas._2011._04.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-31T00:15:10.451+11:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "PpsrCollateralRegistrationRetrieveAttachmentFaultDetail", targetNamespace = "http://schemas.ppsr.gov.au/faults")
public class CollateralRegistrationServiceRetrieveRegistrationAttachmentPpsrCollateralRegistrationRetrieveAttachmentFaultDetailFaultFaultMessage extends Exception {
    
    private au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationRetrieveAttachmentFaultDetail ppsrCollateralRegistrationRetrieveAttachmentFaultDetail;

    public CollateralRegistrationServiceRetrieveRegistrationAttachmentPpsrCollateralRegistrationRetrieveAttachmentFaultDetailFaultFaultMessage() {
        super();
    }
    
    public CollateralRegistrationServiceRetrieveRegistrationAttachmentPpsrCollateralRegistrationRetrieveAttachmentFaultDetailFaultFaultMessage(String message) {
        super(message);
    }
    
    public CollateralRegistrationServiceRetrieveRegistrationAttachmentPpsrCollateralRegistrationRetrieveAttachmentFaultDetailFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public CollateralRegistrationServiceRetrieveRegistrationAttachmentPpsrCollateralRegistrationRetrieveAttachmentFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationRetrieveAttachmentFaultDetail ppsrCollateralRegistrationRetrieveAttachmentFaultDetail) {
        super(message);
        this.ppsrCollateralRegistrationRetrieveAttachmentFaultDetail = ppsrCollateralRegistrationRetrieveAttachmentFaultDetail;
    }

    public CollateralRegistrationServiceRetrieveRegistrationAttachmentPpsrCollateralRegistrationRetrieveAttachmentFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationRetrieveAttachmentFaultDetail ppsrCollateralRegistrationRetrieveAttachmentFaultDetail, Throwable cause) {
        super(message, cause);
        this.ppsrCollateralRegistrationRetrieveAttachmentFaultDetail = ppsrCollateralRegistrationRetrieveAttachmentFaultDetail;
    }

    public au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationRetrieveAttachmentFaultDetail getFaultInfo() {
        return this.ppsrCollateralRegistrationRetrieveAttachmentFaultDetail;
    }
}
