
package au.gov.ppsr.schemas._2011._04.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-31T00:15:10.566+11:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "PpsrCollateralRegistrationUploadAttachmentFaultDetail", targetNamespace = "http://schemas.ppsr.gov.au/faults")
public class CollateralRegistrationServiceUploadRegistrationAttachmentPpsrCollateralRegistrationUploadAttachmentFaultDetailFaultFaultMessage extends Exception {
    
    private au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationUploadAttachmentFaultDetail ppsrCollateralRegistrationUploadAttachmentFaultDetail;

    public CollateralRegistrationServiceUploadRegistrationAttachmentPpsrCollateralRegistrationUploadAttachmentFaultDetailFaultFaultMessage() {
        super();
    }
    
    public CollateralRegistrationServiceUploadRegistrationAttachmentPpsrCollateralRegistrationUploadAttachmentFaultDetailFaultFaultMessage(String message) {
        super(message);
    }
    
    public CollateralRegistrationServiceUploadRegistrationAttachmentPpsrCollateralRegistrationUploadAttachmentFaultDetailFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public CollateralRegistrationServiceUploadRegistrationAttachmentPpsrCollateralRegistrationUploadAttachmentFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationUploadAttachmentFaultDetail ppsrCollateralRegistrationUploadAttachmentFaultDetail) {
        super(message);
        this.ppsrCollateralRegistrationUploadAttachmentFaultDetail = ppsrCollateralRegistrationUploadAttachmentFaultDetail;
    }

    public CollateralRegistrationServiceUploadRegistrationAttachmentPpsrCollateralRegistrationUploadAttachmentFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationUploadAttachmentFaultDetail ppsrCollateralRegistrationUploadAttachmentFaultDetail, Throwable cause) {
        super(message, cause);
        this.ppsrCollateralRegistrationUploadAttachmentFaultDetail = ppsrCollateralRegistrationUploadAttachmentFaultDetail;
    }

    public au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationUploadAttachmentFaultDetail getFaultInfo() {
        return this.ppsrCollateralRegistrationUploadAttachmentFaultDetail;
    }
}
