
package au.gov.ppsr.schemas._2011._04.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-31T00:15:10.236+11:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "PpsrCollateralRegistrationCreateValidationFaultDetail", targetNamespace = "http://schemas.ppsr.gov.au/faults")
public class CollateralRegistrationServiceCreateRegistrationsPpsrCollateralRegistrationCreateValidationFaultDetailFaultFaultMessage extends Exception {
    
    private au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationCreateValidationFaultDetail ppsrCollateralRegistrationCreateValidationFaultDetail;

    public CollateralRegistrationServiceCreateRegistrationsPpsrCollateralRegistrationCreateValidationFaultDetailFaultFaultMessage() {
        super();
    }
    
    public CollateralRegistrationServiceCreateRegistrationsPpsrCollateralRegistrationCreateValidationFaultDetailFaultFaultMessage(String message) {
        super(message);
    }
    
    public CollateralRegistrationServiceCreateRegistrationsPpsrCollateralRegistrationCreateValidationFaultDetailFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public CollateralRegistrationServiceCreateRegistrationsPpsrCollateralRegistrationCreateValidationFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationCreateValidationFaultDetail ppsrCollateralRegistrationCreateValidationFaultDetail) {
        super(message);
        this.ppsrCollateralRegistrationCreateValidationFaultDetail = ppsrCollateralRegistrationCreateValidationFaultDetail;
    }

    public CollateralRegistrationServiceCreateRegistrationsPpsrCollateralRegistrationCreateValidationFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationCreateValidationFaultDetail ppsrCollateralRegistrationCreateValidationFaultDetail, Throwable cause) {
        super(message, cause);
        this.ppsrCollateralRegistrationCreateValidationFaultDetail = ppsrCollateralRegistrationCreateValidationFaultDetail;
    }

    public au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationCreateValidationFaultDetail getFaultInfo() {
        return this.ppsrCollateralRegistrationCreateValidationFaultDetail;
    }
}
