
package au.gov.ppsr.schemas._2011._04.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-31T00:15:10.815+11:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "PpsrCollateralRegistrationSearchValidationFaultDetail", targetNamespace = "http://schemas.ppsr.gov.au/faults")
public class CollateralRegistrationSearchServiceFilterGrantorAndEventDateRangeSearchResultPpsrCollateralRegistrationSearchValidationFaultDetailFaultFaultMessage extends Exception {
    
    private au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationSearchValidationFaultDetail ppsrCollateralRegistrationSearchValidationFaultDetail;

    public CollateralRegistrationSearchServiceFilterGrantorAndEventDateRangeSearchResultPpsrCollateralRegistrationSearchValidationFaultDetailFaultFaultMessage() {
        super();
    }
    
    public CollateralRegistrationSearchServiceFilterGrantorAndEventDateRangeSearchResultPpsrCollateralRegistrationSearchValidationFaultDetailFaultFaultMessage(String message) {
        super(message);
    }
    
    public CollateralRegistrationSearchServiceFilterGrantorAndEventDateRangeSearchResultPpsrCollateralRegistrationSearchValidationFaultDetailFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public CollateralRegistrationSearchServiceFilterGrantorAndEventDateRangeSearchResultPpsrCollateralRegistrationSearchValidationFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationSearchValidationFaultDetail ppsrCollateralRegistrationSearchValidationFaultDetail) {
        super(message);
        this.ppsrCollateralRegistrationSearchValidationFaultDetail = ppsrCollateralRegistrationSearchValidationFaultDetail;
    }

    public CollateralRegistrationSearchServiceFilterGrantorAndEventDateRangeSearchResultPpsrCollateralRegistrationSearchValidationFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationSearchValidationFaultDetail ppsrCollateralRegistrationSearchValidationFaultDetail, Throwable cause) {
        super(message, cause);
        this.ppsrCollateralRegistrationSearchValidationFaultDetail = ppsrCollateralRegistrationSearchValidationFaultDetail;
    }

    public au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationSearchValidationFaultDetail getFaultInfo() {
        return this.ppsrCollateralRegistrationSearchValidationFaultDetail;
    }
}
