
package au.gov.ppsr.schemas._2011._04.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-31T00:15:10.357+11:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "PpsrCollateralRegistrationTransferSingleFaultDetail", targetNamespace = "http://schemas.ppsr.gov.au/faults")
public class CollateralRegistrationServiceTransferSingleRegistrationPpsrCollateralRegistrationTransferSingleFaultDetailFaultFaultMessage extends Exception {
    
    private au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationTransferSingleFaultDetail ppsrCollateralRegistrationTransferSingleFaultDetail;

    public CollateralRegistrationServiceTransferSingleRegistrationPpsrCollateralRegistrationTransferSingleFaultDetailFaultFaultMessage() {
        super();
    }
    
    public CollateralRegistrationServiceTransferSingleRegistrationPpsrCollateralRegistrationTransferSingleFaultDetailFaultFaultMessage(String message) {
        super(message);
    }
    
    public CollateralRegistrationServiceTransferSingleRegistrationPpsrCollateralRegistrationTransferSingleFaultDetailFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public CollateralRegistrationServiceTransferSingleRegistrationPpsrCollateralRegistrationTransferSingleFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationTransferSingleFaultDetail ppsrCollateralRegistrationTransferSingleFaultDetail) {
        super(message);
        this.ppsrCollateralRegistrationTransferSingleFaultDetail = ppsrCollateralRegistrationTransferSingleFaultDetail;
    }

    public CollateralRegistrationServiceTransferSingleRegistrationPpsrCollateralRegistrationTransferSingleFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationTransferSingleFaultDetail ppsrCollateralRegistrationTransferSingleFaultDetail, Throwable cause) {
        super(message, cause);
        this.ppsrCollateralRegistrationTransferSingleFaultDetail = ppsrCollateralRegistrationTransferSingleFaultDetail;
    }

    public au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationTransferSingleFaultDetail getFaultInfo() {
        return this.ppsrCollateralRegistrationTransferSingleFaultDetail;
    }
}
