
package au.gov.ppsr.schemas._2011._04.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-31T00:15:10.588+11:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "PpsrCollateralRegistrationAmendFaultDetail", targetNamespace = "http://schemas.ppsr.gov.au/faults")
public class CollateralRegistrationServiceAmendRegistrationPpsrCollateralRegistrationAmendFaultDetailFaultFaultMessage extends Exception {
    
    private au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationAmendFaultDetail ppsrCollateralRegistrationAmendFaultDetail;

    public CollateralRegistrationServiceAmendRegistrationPpsrCollateralRegistrationAmendFaultDetailFaultFaultMessage() {
        super();
    }
    
    public CollateralRegistrationServiceAmendRegistrationPpsrCollateralRegistrationAmendFaultDetailFaultFaultMessage(String message) {
        super(message);
    }
    
    public CollateralRegistrationServiceAmendRegistrationPpsrCollateralRegistrationAmendFaultDetailFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public CollateralRegistrationServiceAmendRegistrationPpsrCollateralRegistrationAmendFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationAmendFaultDetail ppsrCollateralRegistrationAmendFaultDetail) {
        super(message);
        this.ppsrCollateralRegistrationAmendFaultDetail = ppsrCollateralRegistrationAmendFaultDetail;
    }

    public CollateralRegistrationServiceAmendRegistrationPpsrCollateralRegistrationAmendFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationAmendFaultDetail ppsrCollateralRegistrationAmendFaultDetail, Throwable cause) {
        super(message, cause);
        this.ppsrCollateralRegistrationAmendFaultDetail = ppsrCollateralRegistrationAmendFaultDetail;
    }

    public au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationAmendFaultDetail getFaultInfo() {
        return this.ppsrCollateralRegistrationAmendFaultDetail;
    }
}
