package au.gov.ppsr.schemas._2011._04.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-31T00:15:11.304+11:00
 * Generated source version: 2.7.10
 * 
 */
@WebService(targetNamespace = "http://schemas.ppsr.gov.au/2011/04/services", name = "RegisterOperationsService")
@XmlSeeAlso({ObjectFactory.class, au.gov.ppsr.schemas.faults.ObjectFactory.class, com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class, au.gov.ppsr.schemas._2011._04.data.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RegisterOperationsService {

    @WebResult(name = "IsLaxSupportedResponseMessage", targetNamespace = "http://schemas.ppsr.gov.au/2011/04/services", partName = "parameters")
    @Action(input = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/IsLaxSupported", output = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/IsLaxSupportedResponse")
    @WebMethod(operationName = "IsLaxSupported", action = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/IsLaxSupported")
    public IsLaxSupportedResponseMessage isLaxSupported(
        @WebParam(partName = "parameters", name = "IsLaxSupportedRequestMessage", targetNamespace = "http://schemas.ppsr.gov.au/2011/04/services")
        IsLaxSupportedRequestMessage parameters
    );

    @WebResult(name = "ChangeB2GPasswordResponseMessage", targetNamespace = "http://schemas.ppsr.gov.au/2011/04/services", partName = "parameters")
    @Action(input = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/ChangeB2GPassword", output = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/ChangeB2GPasswordResponse", fault = {@FaultAction(className = RegisterOperationsServiceChangeB2GPasswordPpsrInvalidB2GRequestMessageFaultDetailFaultFaultMessage.class, value = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/ChangeB2GPasswordPpsrInvalidB2GRequestMessageFaultDetailFault"), @FaultAction(className = RegisterOperationsServiceChangeB2GPasswordPpsrIncorrectEnvironmentFaultDetailFaultFaultMessage.class, value = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/ChangeB2GPasswordPpsrIncorrectEnvironmentFaultDetailFault"), @FaultAction(className = RegisterOperationsServiceChangeB2GPasswordPpsrSoapFaultDetailFaultFaultMessage.class, value = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/ChangeB2GPasswordPpsrSoapFaultDetailFault"), @FaultAction(className = RegisterOperationsServiceChangeB2GPasswordPpsrUnauthorisedFaultDetailFaultFaultMessage.class, value = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/ChangeB2GPasswordPpsrUnauthorisedFaultDetailFault"), @FaultAction(className = RegisterOperationsServiceChangeB2GPasswordPpsrStringLengthExceededFaultDetailFaultFaultMessage.class, value = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/ChangeB2GPasswordPpsrStringLengthExceededFaultDetailFault"), @FaultAction(className = RegisterOperationsServiceChangeB2GPasswordPpsrRegisterOperationsChangeB2GPasswordValidationFaultDetailFaultFaultMessage.class, value = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/ChangeB2GPasswordPpsrRegisterOperationsChangeB2GPasswordValidationFaultDetailFault")})
    @WebMethod(operationName = "ChangeB2GPassword", action = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/ChangeB2GPassword")
    public ChangeB2GPasswordResponseMessage changeB2GPassword(
        @WebParam(partName = "parameters", name = "ChangeB2GPasswordRequestMessage", targetNamespace = "http://schemas.ppsr.gov.au/2011/04/services")
        ChangeB2GPasswordRequestMessage parameters
    ) throws RegisterOperationsServiceChangeB2GPasswordPpsrInvalidB2GRequestMessageFaultDetailFaultFaultMessage, RegisterOperationsServiceChangeB2GPasswordPpsrIncorrectEnvironmentFaultDetailFaultFaultMessage, RegisterOperationsServiceChangeB2GPasswordPpsrSoapFaultDetailFaultFaultMessage, RegisterOperationsServiceChangeB2GPasswordPpsrUnauthorisedFaultDetailFaultFaultMessage, RegisterOperationsServiceChangeB2GPasswordPpsrStringLengthExceededFaultDetailFaultFaultMessage, RegisterOperationsServiceChangeB2GPasswordPpsrRegisterOperationsChangeB2GPasswordValidationFaultDetailFaultFaultMessage;

    @WebResult(name = "PingResponseMessage", targetNamespace = "http://schemas.ppsr.gov.au/2011/04/services", partName = "parameters")
    @Action(input = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/Ping", output = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/PingResponse", fault = {@FaultAction(className = RegisterOperationsServicePingPpsrInvalidB2GRequestMessageFaultDetailFaultFaultMessage.class, value = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/PingPpsrInvalidB2GRequestMessageFaultDetailFault"), @FaultAction(className = RegisterOperationsServicePingPpsrIncorrectEnvironmentFaultDetailFaultFaultMessage.class, value = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/PingPpsrIncorrectEnvironmentFaultDetailFault"), @FaultAction(className = RegisterOperationsServicePingPpsrSoapFaultDetailFaultFaultMessage.class, value = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/PingPpsrSoapFaultDetailFault"), @FaultAction(className = RegisterOperationsServicePingPpsrUnauthorisedFaultDetailFaultFaultMessage.class, value = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/PingPpsrUnauthorisedFaultDetailFault"), @FaultAction(className = RegisterOperationsServicePingPpsrStringLengthExceededFaultDetailFaultFaultMessage.class, value = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/PingPpsrStringLengthExceededFaultDetailFault")})
    @WebMethod(operationName = "Ping", action = "http://schemas.ppsr.gov.au/2011/04/services/RegisterOperationsService/Ping")
    public PingResponseMessage ping(
        @WebParam(partName = "parameters", name = "PingRequestMessage", targetNamespace = "http://schemas.ppsr.gov.au/2011/04/services")
        PingRequestMessage parameters
    ) throws RegisterOperationsServicePingPpsrInvalidB2GRequestMessageFaultDetailFaultFaultMessage, RegisterOperationsServicePingPpsrIncorrectEnvironmentFaultDetailFaultFaultMessage, RegisterOperationsServicePingPpsrSoapFaultDetailFaultFaultMessage, RegisterOperationsServicePingPpsrUnauthorisedFaultDetailFaultFaultMessage, RegisterOperationsServicePingPpsrStringLengthExceededFaultDetailFaultFaultMessage;
}
