
package au.gov.ppsr.schemas._2011._04.services;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-02-23T17:25:30.126+11:00
 * Generated source version: 2.7.10
 */

@WebFault(name = "PpsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetail", targetNamespace = "http://schemas.ppsr.gov.au/faults")
public class CollateralRegistrationSearchServiceOrdinalSearchPpsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetailFaultFaultMessage extends Exception {
    
    private au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetail ppsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetail;

    public CollateralRegistrationSearchServiceOrdinalSearchPpsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetailFaultFaultMessage() {
        super();
    }
    
    public CollateralRegistrationSearchServiceOrdinalSearchPpsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetailFaultFaultMessage(String message) {
        super(message);
    }
    
    public CollateralRegistrationSearchServiceOrdinalSearchPpsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetailFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public CollateralRegistrationSearchServiceOrdinalSearchPpsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetail ppsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetail) {
        super(message);
        this.ppsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetail = ppsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetail;
    }

    public CollateralRegistrationSearchServiceOrdinalSearchPpsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetailFaultFaultMessage(String message, au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetail ppsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetail, Throwable cause) {
        super(message, cause);
        this.ppsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetail = ppsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetail;
    }

    public au.gov.ppsr.schemas.faults.PpsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetail getFaultInfo() {
        return this.ppsrCollateralRegistrationSearchOrdinalSearchValidationFaultDetail;
    }
}
